### ISSUE TITLE
401 when downloading a map

### ISSUE THREAD

**Issue by LennyPenny** [nicholastay/NexDirect#1]
```---------------------------

---------------------------
An error has occured whilst downloading MOON LIGHT WAVE (Silleth).

System.Net.WebException: The remote server returned an error: (401) Unauthorized.

   at NexDirectLib.DownloadManager.<DownloadSet>d__8.MoveNext() in D:\Dev\NexDirect\NexDirectLib\DownloadManager.cs:line 64

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)

   at NexDirect.DownloadManagement.<DownloadBeatmapSet>d__5.MoveNext() in D:\Dev\NexDirect\NexDirect\DownloadManagement.cs:line 151
---------------------------
OK   
---------------------------
```

**Comment by nicholastay** [comment]
Are you using Bloodcat to download maps? It seems like they added some captcha recently or something and changed the way beatmaps get downloaded.

If so, perhaps try using the official server option for now, and I can look in to this later as I'm fairly busy with school right now

**Comment by LennyPenny** [comment]
Where is the option to use the official server? 
I'm using the latest release from the release section btw, have not compiled this from source yet so I might be behind

**Comment by nicholastay** [comment]
Click the logo in the bottom right to open the options menu and the option should be there. (maybe I should make this more obvious, people have asked me so much lol)

**Comment by LennyPenny** [comment]
Yup you should def do that.
Thanks btw!

**Comment by nicholastay** [comment]
Just a quick update: if you can build the dev branch yourself, I've added some captcha support for bloodcat downloads - not ideal right now as it uses a chrome browser library that's like 50mb and I really want to slim that down, but it should work for now.
